### PR TITLE
Arackis/properly package

### PR DESCRIPTION
**Pull request by arackaf**
This PR updates your pre-publish script to use svelte-package, as documented [here](https://kit.svelte.dev/docs/packaging), which generates TypeScript types. I've updated your package.json to use "exports" and added the needed "typesVersions" magic as described [here](https://kit.svelte.dev/docs/packaging#typescript) 

With this change, you can import the Dropzone component like this

```
import Dropzone from "svelte-file-dropzone/Dropzone.svelte";
```

which plays well with TypeScript. Also, I believe this library previously used Rollup to compile the Svelte away, which I'm pretty sure is heavily discouraged, ie in case your end user is using a different version of svelte than that which you used to compile it.

If you'd like to test what this looks like, it's deployed to this library.

https://www.npmjs.com/package/arackaf-svelte-file-dropzone 

I left your rollup `build` script in place since I think it *might* be needed for your Storybook? In any event, SvelteKit might be a simpler way to demo the project (see the library template it generates for more info).

Lastly, my previous PR is incorporated into this one 

https://github.com/thecodejack/svelte-file-dropzone/pull/126

### CODE REVIEW

**Comment by arackaf** [comment]
Also just fyi if you've moved on from this project I'd be happy to keep working on it as a collaborator: get rid of the old build stuff, move storybook to SvelteKit, look at old PRs, etc

**Comment by thecodejack** [comment]
Hi @arackaf Thanks for PR. I will add you as maintainer over weekend. Thanks :)

**Comment by arackaf** [comment]
Awesome!!!

**Comment by arackaf** [comment]
I see the GitHub invite, but not npm. Did you send it to arackaf ?

**Comment by thecodejack** [comment]
yes.

image

**Comment by arackaf** [comment]
got it sorry about that - npm is bad about showing pending invites - got it from email though

**Comment by arackaf** [comment]
@thecodejack I got the PR released. I couldn't keep the prior top-level default import working, so I pushed out a 2.0 release, with release notes that the only breaking change is the import to use to get the dropzone component.

I'm gonna work on getting a storybook upgrade PR up soon ...

**Pull request merged**
