### PR TITLE
Add types + Improve bundle output

### PR DESCRIPTION
**Pull request by qurafi**
This pull request adds types for this component. In addition, I noticed the bundle output is invalid and the CSS output is missing. It has no effect on sveltekit or Rollup because they use the "svelte" field directly from package.json. but if it used standalone, it will be broken. I fixed that and removed the index.svelte file because Rollup will treat it as Svelte component and will compile it in the bundle.

### CODE REVIEW

**Comment by thecodejack** [comment]
Thank you for the PR. I am looking into this change and will merge it if all is good.

**Comment by thecodejack** [comment]
@mhmd-22 looks like docs build is failing after change. Can you also fix same before I further check changes?

**Comment by thecodejack** [comment]
Also if possible can you avoid spacing changes for now. We can have a special commit if required. Finding it hard what changes happened.

**Comment by mhmd-22** [comment]
I checked the build logs. looks like a node version mismatch between some dependencies. I will suggest rebuild this project with Sveltekit instead. it has all the tooling we need(typescript out of the box + library packaging). I will suggest also if we move docs from Netlify to Github pages it al lot easier in my opinion.

For spacing changes. Sorry. that my editor doing it automatically. You could provide .prettierrc to avoid this issues

**Comment by mathewcst** [comment]
Hey guys, any updates on this? Would love to have TS support

**Comment by arackaf** [comment]
@mathewcst I've got a PR up to move this project up to svelte-package (ie SvelteKit), linked in the PR is a deployment from my own fork which you can use until mine is merged and deployed 

https://github.com/thecodejack/svelte-file-dropzone/pull/127

**Comment by arackaf** [comment]
Closing this - library should now be built by svelte-package so I'm not sure this is needed. If I'm wrong, feel free to resurrect this and handle the conflicts

**Pull request closed without merging**
