### PR TITLE
Arackis/storybook upgrade

### PR DESCRIPTION
**Pull request by arackaf**
This PR upgrades Storybook to the version that's compatible with SvelteKit, as discussed here: 

https://storybook.js.org/blog/storybook-for-sveltekit/ 

and then gets rid of all the babel, rollup, svelte-loader dependencies :D 

The version (and addons) are still technically beta, but I think I have it working as well as, if not a bit better than the prior version.

The notes addon is deprecated, and no longer working, so I just removed that. I also removed a few addons you no longer need, or were not using (as far as I can tell). But again, everything appears the same as it was. 

All your existing stories are working, and I even have the `Show code` buttons displaying the complete source from each example. 

There's a few imperfections, namely that the "Docs" view shows the first example twice, once at the very top, under the heading "Examples" and then again in line with all the examples. Once this storybook version is released and documented it'll probably be a bit easier to fix things like that.

Only piece left after this merging is to integrate it with your existing Netlify integration, which I don't appear to have access to. The build-storybook script still works, and generates a static build of storybook, which I assume is what Netlify is attaching to, so that shouldn't be too hard (might even work automatically)

### CODE REVIEW

**Comment by arackaf** [comment]
And just fyi, if you're completely done with this project and want to give me access to the repo (I can commit but can't modify settings), I'd be happy to merge the storybook, and fix the live storybook docs (if needed).

**Comment by thecodejack** [comment]
@arackaf looks like there is conflict to fix for this PR

**Review by thecodejack — APPROVED** [review]

**Comment by arackaf** [comment]
@thecodejack 

Ok it's merged, but the storybook link is not updating with the new version (the old still shows fine).

I suspect something broke with the Netlify integration, which is why I was getting all those red X's on my PRs. I suspect the simplest solution would be to just ditch Netlify and host on GitHub pages. I'd be happy to help but I don't have access to set that up.

**Comment by thecodejack** [comment]
netlify doesn't seem to allow add contributors. I am open to setup other place probably github pages itself. Let know what you suggestion is?

**Comment by arackaf** [comment]
@thecodejack my suggestion would be GitHub pages. Happy to try to help, there, but I'll need access to the repo. (or you might be able to fix the Netlify build easily - I assume the build command may have changed in Storyboard??)

**Comment by thecodejack** [comment]
for now I fixed in netlify only.

**Comment by arackaf** [comment]
Sounds great - thanks!!!

**Pull request merged**
